export const HOME_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const LOGOUT_ROUTE = '/logout'
export const ITEMS_ROUTE = '/items'
export const ITEM_CREATE_ROUTE = '/items/create'
export const ITEM_VIEW_ROUTE = '/items/view/:id'
