version: "3.9"
name: fastapivue-dev
services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/migrations/versions/:/app/migrations/versions/
      - ./backend/core/:/app/core
      - ./backend/features/:/app/features
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
