version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #volumes:
    #  - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://username:password@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #volumes:
    #  - ./frontend/src:/app/src
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
