version: "3.9"
name: fastapivue-test
services:
  backend:
    build:
      context: ./backend
      dockerfile: test.Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend/migrations/versions/:/app/migrations/versions/
      - ./backend/core/:/app/core
      - ./backend/features/:/app/features
