"""Items with owner id

Revision ID: 6e8daf547f93
Revises: 00f7a262b2da
Create Date: 2025-01-31 09:36:11.893835

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8daf547f93'
down_revision: Union[str, None] = '00f7a262b2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('DELETE FROM items')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'items', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###
