"""Subitems

Revision ID: e5a8d6a95557
Revises: 6e8daf547f93
Create Date: 2025-03-09 15:39:08.197629

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a8d6a95557'
down_revision: Union[str, None] = '6e8daf547f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subitems_id'), 'subitems', ['id'], unique=False)
    op.create_index(op.f('ix_subitems_item_id'), 'subitems', ['item_id'], unique=False)
    op.create_index(op.f('ix_subitems_owner_id'), 'subitems', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subitems_owner_id'), table_name='subitems')
    op.drop_index(op.f('ix_subitems_item_id'), table_name='subitems')
    op.drop_index(op.f('ix_subitems_id'), table_name='subitems')
    op.drop_table('subitems')
    # ### end Alembic commands ###
